namespace Dfe.Academies.Academisation.IService.ServiceModels.Legacy.ApplicationAggregate;

public record LegacyApplicationServiceModel(
	ICollection<LegacyKeyPersonServiceModel> KeyPersons,
	ICollection<LegacySchoolServiceModel> ApplyingSchools,
	string? Name = null,
	string? TrustName = null,
	string? ApplicationId = null,
	string? ApplicationType = null,
	string? TrustId = null,
	string? FormTrustProposedNameOfTrust = null,
	bool? ApplicationSubmitted = null,
	string? ApplicationLeadAuthorId = null,
	string? ApplicationLeadEmail = null,
	string? ApplicationVersion = null,
	string? ApplicationLeadAuthorName = null,
	string? ApplicationRole = null,
	string? ApplicationRoleOtherDescription = null,
	bool? ChangesToTrust = null,
	string? ChangesToTrustExplained = null,
	bool? ChangesToLaGovernance = null,
	string? ChangesToLaGovernanceExplained = null,
	DateTime? FormTrustOpeningDate = null,
	string? TrustApproverName = null,
	string? TrustApproverEmail = null,
	bool? FormTrustReasonApprovalToConvertAsSat = null,
	string? FormTrustReasonApprovedPerson = null,
	string? FormTrustReasonForming = null,
	string? FormTrustReasonVision = null,
	string? FormTrustReasonGeoAreas = null,
	string? FormTrustReasonFreedom = null,
	string? FormTrustReasonImproveTeaching = null,
	string? FormTrustPlanForGrowth = null,
	string? FormTrustPlansForNoGrowth = null,
	bool? FormTrustGrowthPlansYesNo = null,
	string? FormTrustImprovementSupport = null,
	string? FormTrustImprovementStrategy = null,
	string? FormTrustImprovementApprovedSponsor = null,
	string? ApplicationStatusId = null
);
