# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081


# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Dfe.Academies.Academisation.WebApi/Dfe.Academies.Academisation.WebApi.csproj", "Dfe.Academies.Academisation.WebApi/"]
COPY ["Dfe.Academies.Academisation.Data/Dfe.Academies.Academisation.Data.csproj", "Dfe.Academies.Academisation.Data/"]
COPY ["Dfe.Academies.Academisation.Domain.Core/Dfe.Academies.Academisation.Domain.Core.csproj", "Dfe.Academies.Academisation.Domain.Core/"]
COPY ["Dfe.Academies.Academisation.Domain/Dfe.Academies.Academisation.Domain.csproj", "Dfe.Academies.Academisation.Domain/"]
COPY ["Dfe.Academies.Academisation.Core/Dfe.Academies.Academisation.Core.csproj", "Dfe.Academies.Academisation.Core/"]
COPY ["Dfe.Academies.Academisation.IDomain/Dfe.Academies.Academisation.IDomain.csproj", "Dfe.Academies.Academisation.IDomain/"]
COPY ["Dfe.Academies.Academisation.IService/Dfe.Academies.Academisation.IService.csproj", "Dfe.Academies.Academisation.IService/"]
COPY ["Dfe.Academies.Academisation.Service/Dfe.Academies.Academisation.Service.csproj", "Dfe.Academies.Academisation.Service/"]
RUN --mount=type=secret,id=github_token dotnet nuget add source --username USERNAME --password $(cat /run/secrets/github_token) --store-password-in-clear-text --name github "https://nuget.pkg.github.com/DFE-Digital/index.json" && \
    dotnet restore "./Dfe.Academies.Academisation.WebApi/Dfe.Academies.Academisation.WebApi.csproj"
COPY . .
WORKDIR "/src/Dfe.Academies.Academisation.WebApi"
RUN dotnet build "./Dfe.Academies.Academisation.WebApi.csproj" -c $BUILD_CONFIGURATION -o /app/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Dfe.Academies.Academisation.WebApi.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Dfe.Academies.Academisation.WebApi.dll"]