name: Image build test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  image-build-test:
    name: Image build test
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build
        run: |
          cp .env.development.local.example .env.development.local
          cp .env.database.example .env.database
          docker compose -f docker-compose.yml -p app build
