name: Continuous Integration / Terraform

on:
  push:
    branches: main
    paths:
      - 'terraform/**.tf'
  pull_request:
    paths:
      - 'terraform/**.tf'

jobs:
  continuous-integration-terraform:
    name: Continuous Integration Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Terraform Validate
        uses: DFE-Digital/terraform-linting-actions/.github/actions/validate@v1.2.1
        with:
          terraform_version: '1.10.5'
          tflint_version: 'v0.44.1'
          entrypoint: './terraform'
