name: Cypress Tests using Cypress Docker Image

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      API_KEY:
        required: true
      URL:
        required: true
      SLACK_WEBHOOK_URL:
        required: true
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        type: environment

concurrency:
  group: ${{ github.workflow }}

jobs:
  cypress-tests:
    name: Run Cypress tests
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    strategy:
      matrix:
        browser: [
          "edge"
        ]
    container:
      image: cypress/browsers:22.12.0@sha256:ff80ec791ccabc178cc2a7e33e7b76a92d19992a75efe23939fe19b75319cd53
    defaults:
      run:
        working-directory: CypressTests
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.ref }}

      - name: Run
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_apiKey: ${{ secrets.API_KEY }}
          CYPRESS_url: ${{ secrets.URL }}
        with:
          browser: ${{ matrix.browser }}
          working-directory: CypressTests

      - name: Upload artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
           name: screenshots-${{ inputs.environment }}-${{ matrix.browser }}
           path: CypressTests/cypress/screenshots

      - name: Generate report
        if: always()
        run: |
          mkdir mochareports
          npm run generate:html:report

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: reports-${{ inputs.environment }}-${{ matrix.browser }}
          path: CypressTests/cypress/reports/mocha

      - name: Report results
        if: always()
        run: npm run cy:notify -- --custom-text="Environment ${{ inputs.environment }}, See more information https://github.com/DFE-Digital/academies-academisation-api/actions/runs/${{github.run_id}}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
